apiVersion: skaffold/v2alpha3
kind: Config
build:
  # We build in Google cloud (Cloud Build)
  googleCloudBuild:
    projectId: teak-cyclist-317616
  # Liste of Artifacts
  artifacts:
    # Authentication Service Image
    - image: us.gcr.io/teak-cyclist-317616/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # Tickets Service Image
    - image: us.gcr.io/teak-cyclist-317616/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    # Client Image
    - image: us.gcr.io/teak-cyclist-317616/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
# Deployment specifications
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
