apiVersion: skaffold/v2alpha3
kind: Config
build:
  # We build in Google cloud (Cloud Build) (IMPORTANT: change the image name here and in Depls files)
  #googleCloudBuild:
  #projectId: teak-cyclist-317616
  # We build the project Locally and push to docker regitery
  local:
    push: true
    concurrency: 2
  # Tag policy with the sha256
  tagPolicy:
    sha256: {}
  # Liste of Artifacts
  artifacts:
    # Logs Centralize Service Image
    - image: imadsa/logs-centralize
      context: logs-centralize
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # Logs Worker Service Image
    - image: imadsa/logs-worker
      context: logs-worker
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # Authentication Service Image
    - image: imadsa/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # Tickets Service Image
    - image: imadsa/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    # Orders Service Image
    - image: imadsa/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    # Expiration Service Image
    - image: imadsa/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    # Payment Service Image
    - image: imadsa/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    # Front-end Image
    #- image: imadsa/front-end
      #context: front-end
      #docker:
        #dockerfile: Dockerfile
      #sync:
        #manual:
          #- src: "**/*.js"
            #dest: .
# Deployment specifications
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
