apiVersion: skaffold/v2alpha3
kind: Config
build:
  # We build in Google cloud (Cloud Build) (IMPORTANT: change the image name here and in Depls files)
  #googleCloudBuild:
  #projectId: teak-cyclist-317616
  # We build the project Locally and push to docker regitery
  local:
    push: true
    concurrency: 2
  # Tag policy with the sha256
  tagPolicy:
    sha256: {}
  # Liste of Artifacts
  artifacts:
    # Authentication Service Image
    - image: imadsa/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # Tickets Service Image
    - image: imadsa/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    # Orders Service Image
    - image: imadsa/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    # Client Image
    - image: imadsa/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
# Deployment specifications
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
